version: '3.7'
services:
  web:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
          - db
  db:
    image: postgres:11.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ecp_user
      - POSTGRES_PASSWORD=ecp_password
      - POSTGRES_DB=ecp_django_dev
volumes:
  postgres_data: