# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-04-13 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Отчество')),
                ('lastname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('fullname', models.CharField(max_length=90, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина')], max_length=10, verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('ST', 'Специалист'), ('WR', 'Рабочий'), ('CK', 'Служащий')], max_length=15, verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Posts', verbose_name='Должность'),
        ),
    ]
