# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-04-18 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='post',
            field=models.ForeignKey(on_delete=models.SET('Была удалена из БД'), to='main.Posts', verbose_name='Должность'),
        ),
    ]
