# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-04-14 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_employees_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('Специалист', 'Специалист'), ('Рабочий', 'Рабочий'), ('Служащий', 'Служащий')], max_length=15, verbose_name='Категория'),
        ),
    ]
