# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-04-14 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230414_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='birthday',
        ),
        migrations.AddField(
            model_name='employees',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=10, verbose_name='Пол'),
        ),
    ]
