# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-04-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230418_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Сумма на счету')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Всего')),
            ],
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['lastname', 'firstname', 'surname'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['post'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AddField(
            model_name='posts',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Оклад'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='post',
            field=models.CharField(max_length=30, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Employees', verbose_name='Работник'),
        ),
    ]
