# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-04-27 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230427_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value_int', models.IntegerField(null=True)),
                ('value_str', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SalaryFund',
        ),
    ]
