# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-04-27 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230428_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
